### ISSUE TITLE
Deadlock when performing many inserts to DB

### ISSUE THREAD

**Issue by KFilipek** [pmem/pmse#142]
I found deadlock with error: 
`2017-11-08T06:29:09.059-0500 I STORAGE  [conn56] Failed to lock a shared mutex.: Resource deadlock avoided`
This message occurs at the end of workload and command **db.usertable.count()** give value: **7200042**

numactl -N 1 ./bin/ycsb run mongodb -s -threads 4 -p hdrhistogram.percentiles=95,99,99.9,99.99 -p recordcount=300000000 -p operationcount=7200000 -p readproportion=0.0 -p updateproportion=0.0 -p insertproportion=1.0 -P ./workloads/workloada -p mongodb.url=mongodb://localhost:27017/ycsb?w=0

**Comment by jschmieg** [comment]
Issue not found.Error in scenario.
