### ISSUE TITLE
persistent memory path input

### ISSUE THREAD

**Issue by jongminjeong** [pmem/pmse#174]
Hi, what kinds of path to input when start mongo server
it should be directory?? and

**Comment by jschmieg** [comment]
Hi, It should be directory in which PMSE will create files with indexes and record stores.

**Comment by jongminjeong** [comment]
yes but if i want to store it to persistent memory but its path is not a directory
like /dev/pmem0

**Comment by jschmieg** [comment]
You should create File System with DAX on this /dev/pmem0/ device. Check second part of this blog entry for help:
http://pmem.io/2016/02/22/pm-emulation.html

**Comment by jongminjeong** [comment]
ummm, i know that kind. but i want to store index and record in a persistent memory that not intervene file system.

**Comment by jschmieg** [comment]
If you refer to Device DAX (not /dev/pmemX with DAX enabled file system), then this option is not supported in PMSE.

**Comment by jongminjeong** [comment]
oh..ok thx
