### ISSUE TITLE
Index cursor can't iterate backward

### ISSUE THREAD

**Issue by KFilipek** [pmem/pmse#59]
Reproduction:
Run impacted test, go to mongo shell:
```
t = db.jstests_indexr;
// Iterate forward works
t.find({'a.b': {$gt: 2}, 'a.c': {$lt: 4}}).sort({'a.b': 1}).itcount();
// It returns zero records
t.find({'a.b': {$gt: 2}, 'a.c': {$lt: 4}}).sort({'a.b': -1}).itcount();
```

Impacted test:
indexr.js

**Comment by anidzgor** [comment]
This test passed

**Comment by jschmieg** [comment]
Issue still exists and can be reproduced with YCSB and such query:
db.usertable.find({},{_id:1}).sort({_id:1}).itcount()
3200
db.usertable.find({},{_id:1}).sort({_id:-1}).itcount()
2982
