### ISSUE TITLE
Divide map initialization into small transactions

### ISSUE THREAD

**Issue by KFilipek** [pmem/pmse#91]
Modify function: `void initialize(bool firstRun)` to avoid problems with small pool size in mapper.

**Comment by KFilipek** [comment]
Changed requirements to one big transaction.

**Comment by jschmieg** [comment]
Wasn't the idea behind this issue to divide hashmap initialization into smaller steps that with some logic should speed-up initialization time? It has nothing to do with doing one big transaction during hashmap allocation. Such issue still is valid and can be implemented with many smaller transactions (not one transaction per one entry in hashmap).

**Comment by KFilipek** [comment]
There was problem with initialization big hashmaps, look at the description.

**Comment by jschmieg** [comment]
Description doesn't give any details about problems with big hashmap initialization.
